services:
  db:
    build:
      context: ./db-dev
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  db-mysql:
    build:
      dockerfile: mysql.dockerfile
      context: ./db-dev
    env_file:
      - ./.env
    ports:
      - "3306:3306"


